server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false # eureka에 등록된 서비스 목록으로 자동 라우트 생성
              lower-case-service-id: true
          routes:
            - id: user
              uri: lb://user
              predicates:
                - Path=/users/**
            - id: reservation
              uri: lb://reservation
              predicates:
                - Path=/reservations/**
            - id: accommodation
              uri: lb://accommodation
              predicates:
                - Path=/accommodations/**

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
  instance:
    prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info
  endpoint:
    gateway:
      access: read-only
    health:
      probes:
        enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG