server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/api/user/**
        - id: reservation
          uri: lb://reservation
          predicates:
            - Path=/api/reservation/**
        - id: accommodation
          uri: lb://accommodation
          predicates:
            - Path=/api/accommodation/**
            -
eureka:
  client:
    service-url:
      defaultZone: http://eureka.project.local:8761/eureka/  # eureka → localhost로 변경
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

  logging:
    level:
      org.springframework.cloud.gateway: ERROR