server:
  port: 8080

spring:

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false # discovery(eureka) 에 등록된 서비스 목록 자동 라우트 동적 생성
              lower-case-service-id: true
          routes:
            - id: user
              uri: http://localhost:8081
              predicates:
                - Path=/users/**
            - id: reservation
              uri: http://localhost:8083
              predicates:
                - Path=/reservations/**
            - id: accommodation
              uri: http://localhost:8082
              predicates:
                - Path=/accommodations/**

eureka:
  client:
    # 로드 밸런서의 타겟 그룹에 gateway가 등록되어 있어 모니터링 됨
    # 그래서 eureka 에 등록하지 않았지만
    # gateway가 multi 환경이면 true
    register-with-eureka: false
    fetch-registry: true
  instance:
    prefer-ip-address: true