server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: user
              uri: http://localhost:8081
              predicates:
                - Path=/users/**
            - id: reservation
              uri: http://localhost:8083
              predicates:
                - Path=/reservations/**
            - id: accommodation
              uri: http://localhost:8082
              predicates:
                - Path=/accommodations/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/