server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/users/**
        - id: reservation
          uri: lb://reservation
          predicates:
            - Path=/reservations/**
        - id: accommodation
          uri: lb://accommodation
          predicates:
            - Path=/accommodations/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka.project.local:8761/eureka/
    register-with-eureka: false
    fetch-registry: true
  instance:
    prefer-ip-address: false