server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/api/user/**
        - id: reservation
          uri: lb://reservation
          predicates:
            - Path=/api/reservation/**
        - id: accommodation
          uri: lb://accommodation
          predicates:
            - Path=/api/accommodation/**

  logging:
    level:
      org.springframework.cloud.gateway: DEBUG