server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user
          uri: lb://users
          predicates:
            - Path=/users/**
        - id: reservations
          uri: lb://reservations
          predicates:
            - Path=/reservations/**
        - id: accommodation
          uri: lb://accommodations
          predicates:
            - Path=/accommodations/**

  logging:
    level:
      org.springframework.cloud.gateway: DEBUG