spring:
  cloud:
    config:
      fail-fast: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # eureka → localhost로 변경
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
